apiVersion: v1
kind: Service
metadata:
    name: phpmyadmin
    labels:
        app: phpmyadmin
    annotations:
        metallb.universe.tf/allow-shared-ip: shared-ip
spec:
  type: LoadBalancer
  selector:
    app: phpmyadmin
  ports:
    - port: 5000
      name: http
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  replicas: 1
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: my_phpmyadmin
        imagePullPolicy: Never
        ports:
        - containerPort: 5000