apiVersion: v1
kind: Service
metadata:
    name: wordpress
    labels:
        app: wordpress
    annotations:
        metallb.universe.tf/allow-shared-ip: shared-ip
spec:
  type: LoadBalancer
  selector:
    app: wordpress
  ports:
    - port: 5050
      name: http
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  replicas: 1
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: my_wordpress
        imagePullPolicy: Never
        ports:
        - containerPort: 5050