apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: im_ftps
        imagePullPolicy: Never
        ports:
        - containerPort: 21
        - containerPort: 30021
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  name: ftps-service
spec:
  selector:
    app: ftps
  type: LoadBalancer
  ports:
    - port: 21
      protocol: TCP
      name: port-21
    - port: 30021
      name: port-30021
      protocol: TCP