apiVersion: v1
kind: Service
metadata:
    name: ftps
    labels:
        app: ftps
    annotations:
        metallb.universe.tf/allow-shared-ip: shared-ip
spec:
  type: LoadBalancer
  selector:
    app: ftps
  ports:
    - port: 21
      name: command
      protocol: TCP
    - port: 30000
      name: data
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  replicas: 1
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: my_ftps
        imagePullPolicy: Never
        ports:
        - containerPort: 21
        - containerPort: 30000